# Generated by Django 5.1.5 on 2025-01-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='overdue_status',
        ),
        migrations.AlterField(
            model_name='task',
            name='done_status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(help_text='Укажите дату, к которой нужно заверщить эту задачу', verbose_name='Срок сдачи задачи'),
        ),
    ]
