# Generated by Django 5.1.5 on 2025-01-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_overdue_status_alter_task_done_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'default_related_name': 'tasks', 'ordering': ['start_date', 'slug', 'name'], 'verbose_name': 'задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=1, help_text='Задайте задаче уникальный slug', max_length=64, unique=True, verbose_name='Уникальный slug'),
            preserve_default=False,
        ),
    ]
